# TheHive 5 Configuration for SIEMBA
play.http.secret.key = ${?TH_SECRET}

db.janusgraph {
  storage.backend: berkeleyje
  storage.directory: /opt/thp/thehive/db
  index.search {
    backend: lucene
    directory: /opt/thp/thehive/index
  }
}

storage {
  provider: localfs
  localfs.location: /opt/thp/thehive/files
}

play.http.parser.maxDiskBuffer: 50MB
play.modules.enabled += org.thp.thehive.connector.cortex.CortexConnector

# Allow SIEMBA UI to call TheHive API
play.filters.hosts {
  allowed = ["localhost", "127.0.0.1", "."]
}
