input {
  http {
    port => 8082
    type => "google-workspace"
    codec => "json"
  }
}

filter {
  mutate {
    add_field => {
      "source_integration" => "google"
      "siemba_ingest_time" => "%{@timestamp}"
    }
  }

  if [kind] == "admin#reports#activity" {
    mutate { add_tag => ["google_admin"] }
    if [events][0][name] in ["SUSPICIOUS_LOGIN", "LEAKED_PASSWORD", "ACCOUNT_DISABLED_BY_GOOGLE"] {
      mutate { add_field => { "siemba_severity" => "critical" } }
    } else if [events][0][name] in ["CREATE_APPLICATION_SETTING", "ADD_USER", "CHANGE_USER_PASSWORD"] {
      mutate { add_field => { "siemba_severity" => "medium" } }
    } else {
      mutate { add_field => { "siemba_severity" => "low" } }
    }
  }

  date {
    match => ["id.time", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST:http://127.0.0.1:9200}"]
    index => "siemba-google-%{+YYYY.MM.dd}"
  }
}
